services:
  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
      - "5342:5341"
      - "8082:80"
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    restart: always